### ISSUE TITLE
ERROR: Couldn't find env file: removals_e2etests/mycredentials

### ISSUE THREAD

**Issue by lukebarton** [UKHomeOffice/removals_e2etests#4]
Doesn't succeed with missing file.

Creating empty file works

**Comment by chrisns** [comment]
Not a technical issue per-say, see last section of README.md
https://github.com/UKHomeOffice/removals_e2etests/blob/master/README.md#when-testing-against-remote-environments

Perhaps we could highlight that requirement more, open to suggesiton?

**Comment by lukebarton** [comment]
When I'm running in Dev I don't need any credentials. Therefore I shouldn't
need to create a file.
